### ISSUE TITLE
Use tabular-nums for date & time

### ISSUE THREAD

**Issue by stone-zeng** [quietshu/cssosx#1]
You may add

```css
#system_time {
    font-variant-numeric: tabular-nums;
    font-variant: tabular-nums;
}
```

to make the numbers in date & time to be monospaced.

Compare:

![image](https://user-images.githubusercontent.com/18233088/67632899-17f9f580-f8e4-11e9-8cf4-8256aad27ee6.png)
![image](https://user-images.githubusercontent.com/18233088/67632865-0ca6ca00-f8e4-11e9-84e5-2a7c97db7507.png)
